### ISSUE TITLE
Problem with some Games

### ISSUE THREAD

**Issue by d00p44** [ESPboy-edu/ESPboy_GameBoy#2]
Hey have you checked all the games on function? Because I have a few problems with some games.
for example:
Pokemon(every rom): player only runs upwards
Super Mario 2: espmenu(Start+Select) can't be opened
Final Fantasy: endless loop at startup
i think it's the roms because most of them work fine, but i have no idea how to fix these problems.

**Comment by deltabeard** [comment]
Final Fantasy Legend is not working in Peanut-GB currently (https://github.com/deltabeard/Peanut-GB/issues/80).

**Comment by d00p44** [comment]
> Final Fantasy Legend is not working in Peanut-GB currently ([deltabeard/Peanut-GB#80](https://github.com/deltabeard/Peanut-GB/issues/80)).

oh, thank you for the quick reply....
hope they can fix it :)

**Comment by ESPboy-edu** [comment]
no emulator is perfect.
Some games work, some do not.
And with time emulators evolve and compatibility with some games improves and with some worsens. 
These are the peculiarities)

**Comment by d00p44** [comment]
Yes that's probably true, I just thought it would be helpful to share any noticeable issues :)
I got the espboy mainly as a development platform for my private projects as it is ideal for that. My first goal is a frequency counter with disciplined oscillator, but of course I had to try the gameboy emulator first :D

**Comment by ESPboy-edu** [comment]
It's nice that you like the project and even more nice that you decided to support it by purchasing ESPboy! I hope it helps you in your experiments and doesn't let you down.
It will be cool and interesting for all ESPboy users if you share your crafts in the project forum and Discord chat.
And of course I suggest you try ESPboy AppStore and WebAppStore! )

**Comment by d00p44** [comment]
I got Pokemon running by converting my own rom to C-Header :) 
I also got Warioland and Harvest Moon running successfully... feel free to add them to the collection if you want to :)

https://github.com/d00p44/stuff/blob/main/GB_Roms/

**Comment by deltabeard** [comment]
I've fixed support for Final Fantasy Legend in Peanut-GB now. It should work with ESPboy once the latest changes in Peanut-GB have been pulled.

**Comment by d00p44** [comment]
Thank You!!!
![espboy_finalfantasy](https://user-images.githubusercontent.com/93606145/236580550-821c9c0b-3317-4dff-94e5-9f62ea3ff2d0.png)

**Comment by ESPboy-edu** [comment]
Thanks!
ESPboy GB emu updated
